### ISSUE TITLE
Could you share the post-processing code for getting project demo-like (vector floorplan) results?

### ISSUE THREAD

**Issue by sucream1004** [ennauata/houseganpp#6]
First of all, thanks for the amazing research. I am super interested in this design generation research.

I would like to get cleaner-looking results to see.
In your paper, I found you got a pair-wise comparison with raw segmentation and also vector floorplan.

![image](https://user-images.githubusercontent.com/23395304/159011382-9f39cdcb-dcc3-4883-a575-d89d691a7ee1.png)
I would like to check the results from vector floorplan visualization.

If it is in your github repo already, could you tell me where it is? I didn't see a description of it.

And I have a question about the floorplan result.
Once I got the testing result from test.py with "data/json" using pre-trained weights, I found that some of the results are missing the entrance door.
(filename: 7513.json, 18477.json, 19307.json, 36233.json, 45012.json, 45161,json)

![fp_final_5](https://user-images.githubusercontent.com/23395304/159011063-b7b6f5ba-7beb-4fd2-a0c7-40404a5f3420.png)
![fp_final_0](https://user-images.githubusercontent.com/23395304/159014387-0533227b-e3d4-4d56-88bf-842f67b01fb0.png)

Do you know the reason? I suspect entrance doors are overlapped by other masks.

**Comment by sucream1004** [comment]
I found vectorization code in the testing folder but I don't know what '/home/nelson/Workspace/autodesk/housegan2/raster/0_0.npy' is. Is it just numpy array of raster images?

**Comment by ennauata** [comment]
Hi there, 

Sorry for the delay in responding. In some of our results, the missing front door is due to a mistake made by the network. Sometimes, the mask generated for the front door node can be empty.

I believe '/home/nelson/Workspace/autodesk/housegan2/raster/0_0.npy' should be the masks for each room in the floor plan. I could check if you sent some samples or pointers to the code generating these numpy files.

**Comment by sucream1004** [comment]
Hi,

Thanks. Can you share the vectorization code by any chance?

**Comment by ennauata** [comment]
Yes, it can be found here: https://github.com/ennauata/houseganpp_demo/blob/9c50c9094929d7eb86788226233cf3eda036e3a9/python/viz.py#L172

**Comment by sucream1004** [comment]
Thanks you so much!
